### ISSUE TITLE
Non-commercial license in incorrect_words.yaml

### ISSUE THREAD

**Issue by jbotelho2-bb** [yuki24/did_you_mean#105]
It looks like even though this library is released under MIT License, [evaluation/incorrect_words.yaml](https://github.com/yuki24/did_you_mean/blob/5cfd9112220fe92c4e5ac0f360526711b8097da8/evaluation/incorrect_words.yaml#L3) is released under a non-commercial license. Would it be possible to exclude this from the released gem, given this seems to not be used at runtime?

We noticed this because this gem is bundled with the ruby 2.5 source code, which failed a licensing scan we run internally.

**Comment by yuki24** [comment]
Very good question, thanks for catching that! I'll exclude the entire `evaluation` directory and cut a new release as soon as possible.

**Comment by yuki24** [comment]
[Version 1.2.1](https://github.com/yuki24/did_you_mean/releases/tag/v1.2.1) ships without non-production code that has a non-commercial license. Thanks!
