### ISSUE TITLE
Question: why the Ruby 2.5.0DEV requirement in the latest versions?

### ISSUE THREAD

**Issue by polarapfel** [yuki24/did_you_mean#106]
Hey there,

I noticed gem won't update did_you_mean anymore because it now requires Ruby 2.5.0? That's a bit unfortunate?

thanks,

Tobias

**Comment by yuki24** [comment]
That is [intentional as of today](https://github.com/yuki24/did_you_mean/issues/96#issuecomment-352053443), but I understand this is very annoying. In the next Ruby release, I'll be sure to make the next version compatible with both 2.6 and 2.5 so messages like won't show up.
