### ISSUE TITLE
How to run speed benchmarks?

### ISSUE THREAD

**Issue by colby-swandale** [yuki24/did_you_mean#116]
I'm trying to benchmark a change that i've made in the project, but i'm having issues getting the benchmark to run.

```
$ ruby benchmark/levenshtein/speed.rb
... stack trace
benchmark/levenshtein/speed.rb:9:in `block (2 levels) in <main>': undefined method `before_distance' for DidYouMean::Levenshtein:Module (NoMethodError)
```

I tried using different ruby versions, going to commits from years ago but still cannot get it to work. I'm guessing that those methods are coming from a gem somewhere? Any help would be appreciated 👏

**Comment by yuki24** [comment]
I just add a little more documentation around benchmarking. Would you mind taking a look at [this](https://github.com/yuki24/did_you_mean#benchmarking) and letting me know if anything is unclear? The script seemed a little old and I left that code without rolling back to what it should have looked like.

**Comment by colby-swandale** [comment]
Oh!Thank you so much, those docs are great and resolve my issue. Thank you!!
