### ISSUE TITLE
tmp/.keep packaged in gem

### ISSUE THREAD

**Issue by pvalena** [yuki24/did_you_mean#122]
Hello, could you not package the empty `tmp/.keep` file in rubygems.org gem?

On Fedora we try to avoid unnecessary empty files packaged on a distribution.

**Comment by yuki24** [comment]
I can totally remove that from distributed packages.

Just out of curiosity, what are the reasons why you are following that rule?

**Comment by pvalena** [comment]
> I can totally remove that from distributed packages starting the next release (releases are immutable and can't be updated).

Thanks.

> Just out of curiosity, what are the reasons why you are following that rule?

From what I can tell, it's just a `rpmlint` guideline to keep files on a system relevant. If there was some important reason, it was not documented.
https://fedoraproject.org/wiki/Common_Rpmlint_issues#zero-length

**Comment by pvalena** [comment]
One additional question: is `tmp/` folder for gem runtime? I doubt it as it is not writable.

**Comment by yuki24** [comment]
No, it is only used in test and that test can totally look at other file that permanently exists in the repo. Maybe `did_you_mean.gemspec` is a good one.

**Comment by yuki24** [comment]
fixed by https://github.com/yuki24/did_you_mean/commit/a62833d717a833e2268ff2bec81f4910d6818f0e

**Comment by pvalena** [comment]
Thanks!

**Comment by yuki24** [comment]
released as [`v1.3.1`](https://github.com/yuki24/did_you_mean/releases/tag/v1.3.1).
