### ISSUE TITLE
Bad suggestion for find_or_initialize_by

### ISSUE THREAD

**Issue by dsandstrom** [yuki24/did_you_mean#53]
Ruby 1.9.3 - Rails 3.2.30

```ruby
NoMethodError:
       undefined method `find_or_initialize_by' for #<Class:0x007fb5c0bbb1d8>

           Did you mean? .first_or_initialize
```
```ruby
def find_or_initialize_by(attributes, &block)
  find_by(attributes) || new(attributes, &block)
end
...
def first_or_initialize(attributes = nil, &block)
  first || new(attributes, &block)
end
```
The methods have totally different functionalities: `first_or_initialize` will find the first record, while `find_or_initialize` will find the first record that matches the given attributes.  You might want to change the suggestion to `find_or_initialize_by_attribute` (which I can't find documentation on) or add a cavaet that states you need to prepend `first_or_initialize` with a where clause (`Model.where(attribute: 'something').first_or_initialize`).

**Comment by yuki24** [comment]
I'm not sure about this. This gem doesn't have a brain, thus it's impossible to make a guess that is semantically correct in a certain situation. I'll close this issue, but let me know if you have any suggestion on how we can implement it.
