### ISSUE TITLE
Gem requires 2.3.0dev ?

### ISSUE THREAD

**Issue by tleish** [yuki24/did_you_mean#61]
In trying to upgrade to the latest, I'm given the warning that it requires 2.3.0dev (currently running ruby 2.1.5).  Is this correct?

```
 $ gem update did_you_mean                                                                                                                                     22:57:42
Updating installed gems
Updating did_you_mean
ERROR:  Error installing did_you_mean:
	did_you_mean requires Ruby version >= 2.3.0dev.
```

Is this correct?  gemspec and rubygems.org both indicate: 
```
REQUIRED RUBY VERSION:
>= 1.9.3
```

Note: I just upgraded my OSX, so this could be an un-related issue.

**Comment by yuki24** [comment]
@tleish It's totally correct. The required ruby version (which is `2.3.0dev`) looks incorrect but is actually also correct. The version 1.0.0 has been prepared exclusively for Ruby 2.3 and doesn't work on any other Ruby implementations. I'm not going to talk about the circumstances here, but please use 0.10.0 if you use Ruby 2.2 or older.
