### ISSUE TITLE
How does it work in ruby trunk

### ISSUE THREAD

**Issue by eregon** [yuki24/did_you_mean#63]
Just trying to see how `did_you_mean` works in latest ruby built locally:

```ruby
$ ruby -v -e 'methosd'
ruby 2.3.0dev (2015-12-24 trunk 53280) [x86_64-linux]
-e:1:in `<main>': undefined local variable or method `methosd' for main:Object (NameError)
```
Notice the error message is unchanged.

Should I do anything special to enable it?
`--enable=did_you_mean` seems to not change anything.

**Comment by mttrs** [comment]
Install newer ruby :)

```shell
% ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

%  ruby -v -e 'methosd'
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
-e:1:in `<main>': undefined local variable or method `methosd' for main:Object (NameError)
Did you mean?  methods
               method
```

**Comment by eregon** [comment]
Right, with the released version it works.
When building MRI manually though, I had to `gem install did_you_mean` manually to make it work.
So somehow it seems to behave differently than other "bundled" gems.

**Comment by yuki24** [comment]
@eregon did you have to install all of [these](https://github.com/ruby/ruby/blob/trunk/gems/bundled_gems#L1-L6) or the did_you_mean gem was the only one I had to install manually?

**Comment by eregon** [comment]
@yuki24 It seems none of them is installed by default with just
```bash
autoconf
./configure
make install
```

I guess this is a MRI issue, I'll report there.

**Comment by eregon** [comment]
Reported as https://bugs.ruby-lang.org/issues/11937

**Comment by yuki24** [comment]
@eregon Thanks for filing a issue!
