### ISSUE TITLE
Ruby 2.3.1

### ISSUE THREAD

**Issue by yuki24** [yuki24/did_you_mean#70]
As we are getting closer to the first bugfix release of Ruby 2.3, I'll have to finish all the following to-dos by the time it is out.

 - [x] Backport https://bugs.ruby-lang.org/issues/11928 to Ruby `2.3.0-dev`
 - [x] Cut a new release `v1.0.1` that includes fix 1c52c887c62b0921e799f94bcc4a846dc7cbc057

**Comment by jwaldrip** [comment]
Any update on this. We cannot wait any longer for a fix, it is blocking us from releasing. Maybe at least a way to disable did you mean.

**Comment by beckharvard** [comment]
I'm similarly stuck, Trying to install Canvas (LMS) and no other options at this point.

**Comment by yuki24** [comment]
@jwaldrip If you want to disable the did_you_mean gem you can just uninstall it. Alternatively, use the `--disable-did_you_mean` command line option so Ruby won't require the gem.

Please keep an eye on this Ruby issue https://bugs.ruby-lang.org/issues/11928 if you want to know the status of the bug.

**Comment by Sija** [comment]
Ruby `2.3.1` is out, any news on when could we expect version `1.0.1`?

**Comment by yuki24** [comment]
The DYM version 1.0.1 is out: https://github.com/yuki24/did_you_mean/releases/tag/v1.0.1

**Comment by Dav1nx1** [comment]
How to disable did you mean?

**Comment by yuki24** [comment]
@Dav1nx1 All you have to do is to just uninstall the gem and it'll be disabled.
