### ISSUE TITLE
undefined local variable or method 'foo'; Did you mean 'foo'?

### ISSUE THREAD

**Issue by sunnyrjuneja** [yuki24/did_you_mean#80]
Hi,

I saw this tweet: https://twitter.com/garybernhardt/status/807041495563837440

It seems that if a method or variable is defined conditionally and the program has not entered the conditional, the formatter may still recommend the same method or variable name.

Reproduction:

```ruby
def fun
  if true
    puts(x)
  else x = 1
  end
end
fun()
```

Output:
```
test.rb:3:in `fun': undefined local variable or method `x' for main:Object (NameError)
Did you mean?  x
       from test.rb:7:in `<main>'
```

Maybe we can add a flag if the method/variable called is the same as the recommendation, we output a separate warning.

Let me know what you think. With some guidance, I would love to contribute a patch.

**Comment by yuki24** [comment]
I believe this issue has been fixed. Could you try upgrading to 1.0.2?

**Comment by sunnyrjuneja** [comment]
Looks like it was! Thanks.
