### ISSUE TITLE
May it be possible to detect mis-spelled class names that reside within a sub-"namespace"?

### ISSUE THREAD

**Issue by shevegen** [yuki24/did_you_mean#83]
Hello Yuki Nishijima,

I have a suggestion, which I am not sure if it is trivial 
to add or not. If it is too complicated or too difficult,
please do feel free to close this issue here at any moment
in time!

Now, first, to the problem that I have had:

- I was working on one of my gems just now, called "studium".

This gem uses several different classes, some of which are
within sub-"namespaces", that is, different, cascading 
modules.

To make this more specific, the class I was changing right
now, was the following:

```ruby
  module Studium

  module Exams

  class GroupExamsByTheme < ::Studium::Base
```

So the full namespace to the main class was:

```ruby
  Studium::Exams::GroupExamsByTheme
```

(I could have probably done the above in a single line,
but I actually like to space it out - makes it easier 
for my eyes to spot some mistakes that way. Except for
the coming one. :D )

Now the above was fine, but as I was splitting up code
into separate .rb files, I wrote one class incorrectly:

```ruby
  module Studium

  module Exams

  class GroupExamesByTheme < ::Studium::Base
```

I am not sure if you can easily spot the mistake
above; it took me some minutes to realize what
was going wrong. :D

The mistake that I did was:

- I wrote "GroupExamesByTheme" in the second file,
but it should actually have been "GroupExamsByTheme",
with "Exams" rather than "Exames". I simply wrote
an extra "e".

This error reminds me of "def intialize", which also
happened to me. And your gem also mentions the latter
example.

You also already mention this particular example in
the main readme file, at:

"Correcting a Misspelled Class Name"

However had, I am not quite sure why the above was
not checked through the did_you_mean gem.

In the above example, I would have expected:

      Did you mean?  GroupExamsByTheme

but perhaps the gem can not too easily notice all
errors, since it may be difficult to spot which 
files may be troublemakers, and which code is 
actually meant to be that way.

In my example, though, I have had all code of
that particular class in the same subdirectory,
also called "group_exams_by_theme". Not sure if
this information could also be used by the
did_you_mean gem. I mention this just in case
that it may matter.

The error then was:

    dummy.rb:67:in `run': undefined method `csv_file?' for #<Studium::Exams::GroupExamsByTheme:0x8818078> (NoMethodError)

After making sure that the method csv_file? actually
exists, and that this file was required properly (no
mistake upon require-time), I then looked at the name,
and indeed, I found the mis-spelling part.

Perhaps if the above can not too easily enabled in
the regular code, it could be added to the

    require 'did_you_mean/experimental'

part. Then I could perhaps add this to irb and also
whenever I call the "ruby" binary from the commandline
or something like that; a bit similar to the rubocop
way how to select which errors one wants to have (but
rubocop is more complex and also more complicated 
than the did_you_mean gem, and I like for things to
be simple. I just mentioned this as example).

Anyway, the above code is probably too long, so I tried
to reproduce it with a shorter variant. Perhaps this
one may suffice to showcase the problem.

(1) create two files, called foo.rb and bar.rb

(2) in foo.rb add this content; replace the require
line with the path to the file .bar:

    ```ruby
    require '/Depot/jj/TEST/bar.rb'

    module A

    class Foo

      def initialize
        bar()
      end

    end; end

    A::Foo.new
    ```

(3) create the file bar.rb with this content:

    ```ruby
    module A

    class Fooo
      def bar
        puts 'HI'
      end
    end; end
    ```

The above will not work because "Foo" is misspelled
as "Fooo".

I am not sure how easy it is to add support for this
but perhaps it could be detected in some trivial
cases. Anyway, as written above, if this is too much
work or considered unwanted, no problem! Feel free
to close the issue request at any time. Thanks for
the did_you_mean gem, I think it was a great addition
to ruby.

**Comment by yuki24** [comment]
I don't think it's impossible, but I don't think this is a low-hanging fruit either. There is also a bug in Rails(or `ActiveSupport::Dependencies` more specifically) that completely kills `did_you_mean`'s constant name suggestion feature, and there's a small chance that you might have run into the bug.

Also, as a general suggestion, I wouldn't suggest having multiple files that attempt to define the exact same class. I would instead just keep one file that has all the methods or use modules.
